# Generated by Django 2.0.7 on 2018-07-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chicategory',
            table='chicategory',
        ),
    ]
