# Generated by Django 2.0.7 on 2018-07-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0008_auto_20180731_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(db_column='tgcount', default=0, verbose_name='点赞数'),
        ),
    ]
