# Generated by Django 2.0.7 on 2018-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0009_article_good_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(db_column='tgcount', default=0, max_length=9999999, verbose_name='点赞数'),
        ),
    ]
