# Generated by Django 2.0.7 on 2018-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0010_auto_20180731_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(db_column='tgcount', default=0, verbose_name='点赞数'),
        ),
    ]
