# Generated by Django 2.0.7 on 2018-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_auto_20180718_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='图片'),
        ),
    ]
