# Generated by Django 2.0.7 on 2018-07-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0011_auto_20180731_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.Article')),
            ],
        ),
    ]
