# Generated by Django 2.0.7 on 2018-08-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0014_poll_ip_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='ip_count',
        ),
    ]
