# Generated by Django 2.0.7 on 2018-07-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_auto_20180718_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chicategory',
            options={'verbose_name': '子类名', 'verbose_name_plural': '子类列表'},
        ),
        migrations.AlterField(
            model_name='chicategory',
            name='first_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.Category'),
        ),
    ]
