# Generated by Django 2.0.7 on 2018-08-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0012_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='click_time',
            field=models.DateTimeField(null=True),
        ),
    ]
