# Generated by Django 2.0.7 on 2018-08-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0020_auto_20180806_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images/artpic', verbose_name='图片'),
        ),
    ]
