# Generated by Django 2.0.7 on 2018-08-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0021_auto_20180820_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='artpic', verbose_name='图片'),
        ),
    ]
