# Generated by Django 2.0.7 on 2018-08-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0022_auto_20180820_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/artpic', verbose_name='图片'),
        ),
    ]
