# Generated by Django 2.0.7 on 2018-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0013_poll_click_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ip_count',
            field=models.IntegerField(default=0),
        ),
    ]
