# Generated by Django 2.0.7 on 2018-08-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0017_comments_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'pub_time', 'ordering': ['-last_mod_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
    ]
