# Generated by Django 2.0.7 on 2018-08-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0018_auto_20180806_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_time', 'ordering': ['-pub_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
    ]
