# Generated by Django 2.0.7 on 2018-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0019_auto_20180806_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_time', 'ordering': ['create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/artpic', verbose_name='图片'),
        ),
    ]
